# Generated by Django 5.1.6 on 2025-03-10 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.permissions.scripts import create_permission
def forward(apps, schema_editor):
    create_permission()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('retrieve', 'Retrieve'), ('delete', 'Delete'), ('action', 'Action')], max_length=20)),
                ('group', models.CharField(choices=[('dashboard', 'Dashboard'), ('report', 'Report'), ('user', 'User'), ('configuration', 'Configuration'), ('license', 'License'), ('partner', 'Partner'), ('area', 'Area'), ('asset', 'Asset'), ('unit', 'Unit')], max_length=50)),
            ],
            options={
                'unique_together': {('permission', 'group')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('agent', 'Agent'), ('owner', 'Owner'), ('customer', 'Customer')], max_length=30)),
                ('permission', models.ManyToManyField(blank=True, related_name='role_permissions', related_query_name='role', to='permissions.permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ManyToManyField(blank=True, related_name='user_permissions', related_query_name='user', to='permissions.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward, migrations.operations.special.RunPython.noop)
    ]
