# Generated by Django 5.1.6 on 2025-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('report', 'Report'), ('user', 'User'), ('configuration', 'Configuration'), ('license', 'License'), ('partner', 'Partner'), ('area', 'Area'), ('asset', 'Asset'), ('unit', 'Unit'), ('inquiry', 'Inquiry'), ('wish-list', 'Wish List')], max_length=50),
        ),
    ]
